export const cubaProvinces = [
	"Pinar del Río",
	"Artemisa",
	"La Habana",
	"Mayabeque",
	"Matanzas",
	"Villa Clara",
	"Cienfuegos",
	"Sancti Spíritus",
	"Ciego de Ávila",
	"Camagüey",
	"Las Tunas",
	"Holguín",
	"Granma",
	"Santiago de Cuba",
	"Guantánamo",
	"Isla de la Juventud", // Municipio Especial
];

export const categories = [
	"Base de Datos",
	"Programación",
	"Inteligencia Artificial",
	"Redes y Seguridad",
	"Sistemas Operativos",
	"Diseño Web",
	"Ciencia de Datos",
	"Arquitectura de Computadoras",
	"Algoritmos y Estructuras de Datos",
	"Ingeniería de Software",
	"Teoría de la Computación",
	"Matemáticas para la Computación",
	"Gráficos por Computadora",
	"Interacción Humano-Computadora",
	"Realidad Virtual y Aumentada",
	"Robótica",
	"Ciberseguridad",
	"Desarrollo de Videojuegos",
	"Aprendizaje Automático",
	"Lenguajes de Programación",
	"Computación Cuántica",
];

export const languages = [
	"Español",
	"Inglés",
	"Francés",
	"Alemán",
	"Italiano",
	"Portugués",
	"Ruso",
	"Chino",
	"Japonés",
	"Coreano",
	"Árabe",
	"Hindi",
];

export const profesorDepartment = [
	"Informática",
	"Matemáticas",
	"Física",
	"Ingeniería de Software",
	"Inteligencia Artificial",
	"Redes y Seguridad",
	"Ciencia de Datos",
	"Sistemas Operativos",
	"Arquitectura de Computadoras",
	"Algoritmos y Estructuras de Datos",
	"Teoría de la Computación",
	"Gráficos por Computadora",
	"Interacción Humano-Computadora",
	"Realidad Virtual y Aumentada",
	"Robótica",
	"Ciberseguridad",
	"Desarrollo de Videojuegos",
	"Lenguajes de Programación",
	"Computación Cuántica",
];
